{
 "title": "TrueNAS CORE v13",
 "description": "Replicates the TrueNAS CORE \"Reporting\" metrics and expects a Graphite data source.",
 "tags": [ "truenas" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {}
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {}
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {}
   },
   {
    "name": "mount",
    "label": "Mount",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "servers.$server.uptime.uptime" }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(diffSeries(sumSeries(servers.$server.memory.memory.*), servers.$server.memory.memory.free, servers.$server.zfs_arc.cache_size.arc), \"services\")"
    },
    {
     "target": "alias(servers.$server.memory.memory.free, \"free\")"
    },
    {
     "target": "alias(servers.$server.zfs_arc.cache_size.arc, \"zfs_cache\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "offset(scale(servers.$server.aggregation.cpu_average.gauge.idle, -1), 100)"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "offset(scale(avg(servers.$server.cputemp.*.temperature), 0.1), -273.15)"
    }
   ]
  },
  {
   "title": "Disk Temperature (Top 5)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(highestCurrent(servers.$server.disktemp.$disk.temperature, 5),\".*disktemp\\.(.*)\\.temperature\", \"\\1\")"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "sumSeries(servers.$server.memory.memory.*)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Average)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.aggregation.cpu_average.gauge.*)"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.load.load.*)"
      }
     ]
    },
    {
     "title": "CPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "target": "offset(scale(avg(servers.$server.cputemp.*.temperature), 0.1), -273.15)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Temperature",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.disktemp.$disk.temperature, \".*disktemp\\.(.*)\\.temperature\", \"\\1\")"
      }
     ]
    },
    {
     "title": "Disk Busy",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByMetric(roundFunction(servers.$server.geom_stat.geom_busy_percent.$disk, 2))"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.geom_stat.geom_latency.$disk.{read,write}, \".*geom_latency\\.(.*)\\.(.*)\", \"\\1 \\2\")"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.geom_stat.geom_ops.$disk)"
      }
     ]
    },
    {
     "title": "Pending I/O Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.geom_stat.geom_queue.$disk)"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.geom_stat.geom_bw.$disk.{read,write}, \".*geom_bw\\.(.*)\\.(.*)\", \"\\1 \\2\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.memory.memory.*)"
      }
     ]
    },
    {
     "title": "Swap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.swap.swap.*)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Traffic",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.interface.$interface.if_octets.*, \".*interface\\.(.*)\\.if_octets\\.(.*)\", \"\\1 \\2\")"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Stats (Operations)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.nfsstat.server.nfsstat.{read,write})"
      }
     ]
    },
    {
     "title": "NFS Stats (Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.nfsstat.server.nfsstat.{read_bytes,write_bytes}, \".*nfsstat\\.(.*)_bytes\", \"\\1\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Free Space (mount)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.df.$mount.df_complex.free, \".*\\.(.*)\\.df_complex.*\", \"\\1\")"
      }
     ]
    },
    {
     "title": "Filesystem Free Space (root)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "servers.$server.df.root.df_complex.free"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.processes.ps_state.*)"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "target": "servers.$server.uptime.uptime" }
     ]
    }
   ]
  },
  {
   "title": "Target",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "SCSI target port iscsi",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.ctl.iscsi.disk_octets.{read,write})"
      }
     ]
    },
    {
     "title": "SCSI target port TCP",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.ctl.tpc.disk_octets.{read,write})"
      }
     ]
    }
   ]
  },
  {
   "title": "ZFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.zfs_arc.cache_size.{arc,L2})"
      }
     ]
    },
    {
     "title": "ARC Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.mylo_truenas1_lan_redit_name.zfs_arc.cache_ratio.arc)"
      }
     ]
    },
    {
     "title": "ARC Requests demand_data",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.zfs_arc.cache_result.{demand_data_hit,demand_data_miss}, \".*data_(.*)\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests demand_metadata",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.zfs_arc.cache_result.{demand_metadata_hit,demand_metadata_miss}, \".*metadata_(.*)\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests prefetch_data",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.zfs_arc.cache_result.{prefetch_data_hit,prefetch_data_miss}, \".*prefetch_data_(.*)\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests prefetch_metadata",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(servers.$server.zfs_arc.cache_result.{prefetch_metadata_hit,prefetch_metadata_miss}, \".*prefetch_metadata_(.*)\", \"\\1\")"
      }
     ]
    }
   ]
  },
  {
   "title": "ZFS v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.$server.zfs_arc_v2.{gauge_arcstats_raw_size,gauge_arcstats_raw}.{size,l2_size})"
      }
     ]
    },
    {
     "title": "ARC Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasByMetric(servers.mylo_truenas1_lan_redit_name.zfs_arc_v2.arcstat_ratio_arc.{hits,l2_hits})"
      }
     ]
    },
    {
     "title": "ARC Requests demand_data",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(scale(servers.$server.zfs_arc_v2.gauge_arcstats_raw_demand.{demand_data_hits,demand_data_misses}, 0.1), \".*_(hits|misses),.*\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests demand_metadata",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(scale(servers.$server.zfs_arc_v2.gauge_arcstats_raw_demand.{demand_metadata_hits,demand_metadata_misses}, 0.1), \".*_(hits|misses),.*\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests prefetch_data",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(scale(servers.$server.zfs_arc_v2.gauge_arcstats_raw_prefetch.{prefetch_data_hits,prefetch_data_misses}, 0.1), \".*prefetch_data_(.*),.*\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ARC Requests prefetch_metadata",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "target": "aliasSub(scale(servers.$server.zfs_arc_v2.gauge_arcstats_raw_prefetch.{prefetch_metadata_hits,prefetch_metadata_misses}, 0.1), \".*prefetch_metadata_(.*),.*\", \"\\1\")"
      }
     ]
    }
   ]
  }
 ]
}